name: Download USAGE license metadata
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

permissions:
  contents: write
  id-token: write

jobs:
  download-and-process:
    name: Download and process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install -r scripts/requirements.txt
          python scripts/process_spreadsheet.py "${{ vars.LICENSES_XLSX_URL }}"
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'catalog'
          message: Update USAGE License definitions